name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  maven-build:
    name: Build and Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -T1C package

      - name: Extract metadata (tags, labels) for aaa
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: registry.flux.host/aaa

      - name: Generate Flux Host JWT
        id: jwt
        uses: ./.github/actions/generate-jwt
        with:
          api-key: ${{ secrets.FLUX_HOST_API_KEY }}

      - name: Log in to Flux Host Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.flux.host
          username: ${{ steps.jwt.outputs.userId }}
          password: ${{ steps.jwt.outputs.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

      - name: Deploy to Flux Host
        uses: ./.github/actions/deploy-application
        with:
          cluster-name: "Training"
          application-name: "Pitstop"
          metadata-json: ${{ steps.docker-meta.outputs.json }}
          token: ${{ steps.jwt.outputs.token }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com

      - name: Build
        run: |
          cd ui
          npm install
          npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'pitstop'
          directory: 'dist/pitstop'
